### ISSUE TITLE
Proposal: Plugin system for Beta

### ISSUE THREAD

**Issue by kubaj** [flowup/mmo#48]
# Plugin system proposal
Plugins can be divided to two groups:
* service plugins - generators, ...
* global plugins - deployment, ...

Global plugins will have access to all service's source code.
Service plugins will have access only to its service's source code.

Plugins will have access to project information - project name, service name. 

## Plugin declaration
Global plugins can be declared in mmo.yaml file in root of the project. Service's plugins can be declared in a service's folder in file mmo-plugins.yaml
```yaml
plugins:
 - name: global-plugin:version
   volumes: ...
   env: ...
---
plugins:
 - name: plugin-name:version
   nethost: true
```
## Access to configuration
Configuration will be exported to env variables, there won't be lot of exported fields because lot of configuration is done using plugins. The most important part of the configuration is name of the project in my opinion.

Go library for config loading will be also available for cases that plugin will be golang based templater.

## Plugin manifest
Plugin must have plugin manifest `/plugins/mmo-plugin.yaml` that looks like following:
```yaml
name: Go gRPC generator  # Name of the plugin
hooks:                   # Plugin hooks (description of hooks is below)
  gen: gen.sh
```
## Hooks
Plugin must have scope `hooks` in plugin manifest. Hooks are entrypoints of the plugin which are run at different stages of the mmo lifecycle.
List of the hooks:
 * gen - run on `mmo gen` and `mmo init` is run
 * build - run on `mmo build` and `mmo run`, `mmo ci` 
 * test - run on `mmo test` and `mmo ci`
 * run - run on `mmo run`
 * deploy - run on `mmo deploy`

### Volume mounting
You can mount files and folders to plugin using `volumes`: 
```yaml
volumes:
  - host: /path1   # Path in your computer
    plugin: /path2 # Path in plugin
  - host: /another/path/in/system
    plugin: /gen
```

### Exporting variables
You can export variables to plugin using `env`:
```yaml
env:
  - name: SOME_VAR
    value: x
  - name: ANOTHER_VARIABLE
    value: y
```

### Attaching to host network
You can attach plugin to host network to host network using option `hostnet: true`. This adds possibility of the container access web servers running locally such as minikube API.

### Attaching to docker
You can permit plugin to access your docker server using option `docker: true`. This option should have only plugins that are building docker images.

## Shared configs
MMO will support shared configs - multiple services can share one config defined in scope `plugin-config` in `mmo.yaml`. This shared config can be added to plugin config to `config`:
```yaml
...
services:
  service1:
    plugins:
     - name: some-plugin:version
       config: mmo.yaml/config1 # config1 config in plugin-config section of file mmo.yaml 
       config: service/mmo-plugin.yaml/config1 # config1 config in plugin-config section of file service/mmo-plugin.yaml 

plugin-config:
  config1:
    volumes:
      - host: /path1
        plugin: /path2
    env:
      - name: SOME_VAR
        value: x
...
```
In case that plugin will contain `config` and explicit configuration options, then explicit configuration will overwrite shared configuration.
